
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdur-Rafay
 */
public class Home_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    public CreateCode LatexCode;
    
    public Home_GUI() throws IOException {
        initComponents();
        DateTextField.setText(LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CourseLabel = new javax.swing.JLabel();
        CourseTextField = new javax.swing.JTextField();
        TopicLabel = new javax.swing.JLabel();
        TopicTextField = new javax.swing.JTextField();
        InstructorLabel = new javax.swing.JLabel();
        InstructorTextField = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        DateTextField = new javax.swing.JTextField();
        NextButton = new javax.swing.JButton();
        CreateTitleLabel = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CourseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CourseLabel.setText("Course");

        CourseTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CourseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseTextFieldActionPerformed(evt);
            }
        });

        TopicLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TopicLabel.setText("Topic");

        TopicTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        InstructorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstructorLabel.setText("Instructor");

        InstructorTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        DateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DateLabel.setText("Date");

        DateTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        NextButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        CreateTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CreateTitleLabel.setText("Create Title");

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopicLabel)
                    .addComponent(InstructorLabel)
                    .addComponent(DateLabel)
                    .addComponent(CourseLabel))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(InstructorTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(TopicTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CourseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateTextField))
                .addGap(0, 177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateTitleLabel)
                .addGap(297, 297, 297))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(CreateTitleLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TopicLabel)
                    .addComponent(TopicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstructorLabel)
                    .addComponent(InstructorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CourseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseTextFieldActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        
        if(CourseTextField.getText().equals("") || TopicTextField.getText().equals("") || InstructorTextField.getText().equals("") || DateTextField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please fill the required fields");
        else{
            
            try {
                LatexCode = new CreateCode();
                LatexCode.MakeTitle(CourseTextField.getText(), TopicTextField.getText(), InstructorTextField.getText(), DateTextField.getText());
                JOptionPane.showMessageDialog(null,"Title Created Successfully");
                AddSections_And_Subsections_GUI SS = new AddSections_And_Subsections_GUI(LatexCode);
                SS.setVisible(true);
                this.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Home_GUI.class.getName()).log(Level.SEVERE, null, ex);
                
            }
            
        }
        
        
    }//GEN-LAST:event_NextButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
       
        System.exit(0);
        
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home_GUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Home_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JTextField CourseTextField;
    private javax.swing.JLabel CreateTitleLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel InstructorLabel;
    private javax.swing.JTextField InstructorTextField;
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel TopicLabel;
    private javax.swing.JTextField TopicTextField;
    // End of variables declaration//GEN-END:variables
}
